# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  build:
    environment:
      LEXICON_DIR: /opt/db/
      AUTH_KEY: abcdef
    docker:
      # specify the version
      - image: golang:alpine

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    #### TEMPLATE_NOTE: go expects specific checkout path representing url
    #### expecting it in the form of
    ####   /go/src/github.com/circleci/go-tool
    ####   /go/src/bitbucket.org/circleci/go-tool
    working_directory: /go/src/github.com/domino14/macondo
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "ad:9e:01:fa:fa:e7:03:a4:49:74:98:91:52:a8:dc:3c"
      - run:
          name: Install git, ssh, and build-base (for tests)
          command: apk update && apk upgrade && apk add git openssh build-base
      - run:
          name: Install ssl
          command: apk add --update ca-certificates openssl && update-ca-certificates
      - run: if [ ! -n "$(grep "^bitbucket.org " ~/.ssh/known_hosts)" ]; then ssh-keyscan bitbucket.org >> ~/.ssh/known_hosts 2>/dev/null; fi
      - run:
          name: Clone word dbs Webolith repo
          command: git clone git@bitbucket.org:cesar_del_solar/webolith-word-dbs.git /opt/webolith-word-dbs
      - run: mkdir $LEXICON_DIR
      - run: cd /opt/webolith-word-dbs && tar xzvf dbs.tar.gz
      - run: mv /opt/webolith-word-dbs/*.db $LEXICON_DIR
      # specify any bash command here prefixed with `run: `
      - run: go test -v ./...
