name: Build and Upload Release Artifacts

permissions:
  contents: write

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: ">=1.22"

      - name: Install invoke
        run: |
          python -m pip install --upgrade pip
          pip install invoke

      - name: Download a couple of lexica
        run: |
          mkdir -p data/lexica/gaddag
          curl -L https://github.com/woogles-io/liwords/raw/master/liwords-ui/public/wasm/2024/NWL23.kwg -o data/lexica/gaddag/NWL23.kwg
          curl -L https://github.com/woogles-io/liwords/raw/master/liwords-ui/public/wasm/2024/CSW21.kwg -o data/lexica/gaddag/CSW21.kwg

      - name: Run build script
        run: inv build

      - name: Release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: |
            macondo-*.zip
