name: Build and Deploy

on:
  push:
    branches:
      - "*"

permissions:
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      MACONDO_DATA_PATH: /opt/data
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Clone lexicon repo
        uses: actions/checkout@v4
        with:
          repository: domino14/word-game-lexica
          path: word-game-lexica

      - run: mv $GITHUB_WORKSPACE/word-game-lexica /opt/word-game-lexica
      - run: cp -r data /opt/data
      - run: mkdir -p /opt/data/lexica/gaddag
      - run: mv /opt/word-game-lexica/gaddag/*.kwg /opt/data/lexica/gaddag

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: ">=1.22"

      - name: Build
        run: make

      - name: Run tests
        run: go test $(go list ./... | grep -v wasm)

      - name: Discord notification
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        uses: Ilshidur/action-discord@master
        with:
          args: "Macondo backend built successfully for branch {{GITHUB_REF_NAME}}."
